import type { CommandDefinition } from "./fleck-data";

/**
 * Mock command registry shaped exactly like `fleck-core::command`'s
 * `CommandDefinition`s. The Rust registry currently ships one real command
 * (`workspace.rename`); the rest are placeholders the engine will register as
 * later tasks land. The UI treats every entry uniformly, so swapping this list
 * for the backend's `get_commands` response requires no component changes.
 */
export const COMMAND_DEFINITIONS: CommandDefinition[] = [
  {
    id: "workspace.rename",
    label: "Rename workspace",
    description: "Rename the current workspace.",
    group: "workspace",
    aliases: ["set workspace name", "rename document"],
    shortcut: "F2",
    undoable: true,
    parameterPrompts: [{ key: "name", label: "Name", kind: "string", required: true }],
  },
  {
    id: "workspace.open",
    label: "Open workspace",
    description: "Open a .fleck workspace file.",
    group: "workspace",
    aliases: ["open file"],
    shortcut: "⌘O",
    undoable: false,
    parameterPrompts: [],
  },
  {
    id: "workspace.save",
    label: "Save workspace",
    description: "Save the current workspace to disk.",
    group: "workspace",
    aliases: ["write file"],
    shortcut: "⌘S",
    undoable: false,
    parameterPrompts: [],
  },
  {
    id: "image.open",
    label: "Open image",
    description: "Import an image into the workspace.",
    group: "workspace",
    aliases: ["import image", "place image"],
    undoable: true,
    parameterPrompts: [],
  },
  {
    id: "layer.create",
    label: "Add layer",
    description: "Create a new empty raster layer.",
    group: "layer",
    aliases: ["new layer", "add layer"],
    shortcut: "⌘⇧N",
    undoable: true,
    parameterPrompts: [],
  },
  {
    id: "layer.duplicate",
    label: "Duplicate layer",
    description: "Duplicate the selected layer.",
    group: "layer",
    aliases: ["copy layer"],
    shortcut: "⌘J",
    undoable: true,
    parameterPrompts: [],
  },
  {
    id: "layer.rename",
    label: "Rename layer",
    description: "Rename the selected layer.",
    group: "layer",
    aliases: ["name layer"],
    shortcut: "F2",
    undoable: true,
    parameterPrompts: [{ key: "name", label: "Name", kind: "string", required: true }],
  },
  {
    id: "layer.delete",
    label: "Delete layer",
    description: "Delete the selected layer.",
    group: "layer",
    aliases: ["remove layer"],
    undoable: true,
    parameterPrompts: [],
  },
  {
    id: "layer.merge_down",
    label: "Merge layer down",
    description: "Merge the selected layer into the one below it.",
    group: "layer",
    aliases: ["merge layer"],
    undoable: true,
    parameterPrompts: [],
  },
  {
    id: "layer.flatten",
    label: "Flatten visible layers",
    description: "Flatten all visible layers into a single raster layer.",
    group: "layer",
    aliases: ["flatten image"],
    undoable: true,
    parameterPrompts: [],
  },
  {
    id: "layer.group",
    label: "Group layer",
    description: "Create a group from the selected layer.",
    group: "layer",
    aliases: ["new group"],
    undoable: true,
    parameterPrompts: [{ key: "name", label: "Group name", kind: "string", required: true }],
  },
  {
    id: "selection.crop",
    label: "Crop to selection",
    description: "Crop the working bounds to the current selection.",
    group: "selection",
    aliases: ["trim to selection"],
    shortcut: "⌘⇧X",
    undoable: true,
    parameterPrompts: [],
  },
  {
    id: "selection.trim-transparent",
    label: "Trim transparent pixels",
    description: "Remove fully transparent borders.",
    group: "selection",
    aliases: ["autotrim", "trim alpha"],
    undoable: true,
    parameterPrompts: [],
  },
  {
    id: "edit.resize-canvas",
    label: "Resize canvas",
    description: "Change the canvas dimensions.",
    group: "view",
    aliases: ["canvas size"],
    undoable: true,
    parameterPrompts: [
      { key: "width", label: "Width (px)", kind: "number", required: true },
      { key: "height", label: "Height (px)", kind: "number", required: true },
    ],
  },
  {
    id: "edit.brightness-contrast",
    label: "Adjust brightness & contrast",
    description: "Tune brightness and contrast on the active layer.",
    group: "view",
    aliases: ["levels"],
    undoable: true,
    parameterPrompts: [
      { key: "brightness", label: "Brightness", kind: "number", required: false },
      { key: "contrast", label: "Contrast", kind: "number", required: false },
    ],
  },
  {
    id: "export.area-selected",
    label: "Export selected area",
    description: "Export the currently selected export area.",
    group: "export",
    aliases: ["export current"],
    shortcut: "⌘E",
    undoable: false,
    parameterPrompts: [],
  },
  {
    id: "export.all",
    label: "Export all areas",
    description: "Export every export area in the workspace.",
    group: "export",
    aliases: ["export everything"],
    shortcut: "⌘⇧E",
    undoable: false,
    parameterPrompts: [],
  },
  {
    id: "export.copy-base64",
    label: "Copy as Base64",
    description: "Copy the export result as a Base64 string.",
    group: "export",
    aliases: ["copy data uri base64"],
    undoable: false,
    parameterPrompts: [],
  },
  {
    id: "export.copy-markdown",
    label: "Copy as Markdown image",
    description: "Copy the export result as Markdown image syntax.",
    group: "export",
    aliases: ["copy md image"],
    undoable: false,
    parameterPrompts: [],
  },
  {
    id: "recipe.favicon",
    label: "Generate favicon pack",
    description: "Run the favicon recipe to produce a full icon set.",
    group: "recipe",
    aliases: ["favicon recipe", "make favicons"],
    undoable: true,
    parameterPrompts: [],
  },
  {
    id: "recipe.app-icon",
    label: "Generate app icon set",
    description: "Run the app-icon recipe across platform sizes.",
    group: "recipe",
    aliases: ["app icons recipe"],
    undoable: true,
    parameterPrompts: [],
  },
  {
    id: "recipe.remove-bg",
    label: "Remove background and trim",
    description: "Remove the background, then trim transparent pixels.",
    group: "recipe",
    aliases: ["cutout", "knockout background"],
    undoable: true,
    parameterPrompts: [],
  },
  {
    id: "view.toggle-pixel-grid",
    label: "Toggle pixel grid",
    description: "Show or hide the pixel grid overlay.",
    group: "view",
    aliases: ["pixel grid"],
    shortcut: "⌘'",
    undoable: false,
    parameterPrompts: [],
  },
  {
    id: "view.zoom-export-area",
    label: "Zoom to export area",
    description: "Fit the viewport to the selected export area.",
    group: "view",
    aliases: ["fit export area"],
    undoable: false,
    parameterPrompts: [],
  },
];
